# Generated by Django 4.2.1 on 2023-11-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='background_check',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='personal_statement',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='preferred_grade_level',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='salary_expectations',
        ),
        migrations.RemoveField(
            model_name='students',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='students',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='students',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='students',
            name='school_segment',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school_segment',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='staff',
        ),
        migrations.AddField(
            model_name='staffs',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.educationlevel'),
        ),
        migrations.AddField(
            model_name='students',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.educationlevel'),
        ),
        migrations.AddField(
            model_name='students',
            name='selected_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.class_level'),
        ),
        migrations.AddField(
            model_name='subject',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.educationlevel'),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedbackcooker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedbackparent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedbackschoolcleaner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedbackschooldriver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedbackschoolsecurityperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedbackstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavereportcooker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavereportparent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavereportschoolcleaner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavereportschooldriver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavereportschoolsecurityperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavereportstaffs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leavereportstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationcooker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationparent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationschoolcleaner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationschooldriver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationschoolsecurityperson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationstaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notificationstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='staff_cv'),
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='other_certificates',
            field=models.FileField(blank=True, null=True, upload_to='staff_other_certificates'),
        ),
        migrations.AlterField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='certificate_url',
            field=models.FileField(blank=True, null=True, upload_to='staff_skill_certificate'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='birth_certificate_photo',
            field=models.FileField(blank=True, null=True, upload_to='stass_birth_certificate_photo'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='staff_profile_pic'),
        ),
        migrations.AlterField(
            model_name='students',
            name='birth_certificate_photo',
            field=models.FileField(blank=True, null=True, upload_to='student_birth_certificate_photos/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='student_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('selected_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.class_level')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subject')),
            ],
        ),
    ]
