# Generated by Django 4.2.1 on 2023-11-24 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_remove_result_current_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_routes', to='student_management_app.route'),
        ),
        migrations.AlterField(
            model_name='route',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='route_students', to='student_management_app.students'),
        ),
    ]
