# Generated by Django 4.2.1 on 2023-11-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_students_route_alter_route_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='route',
        ),
        migrations.RemoveField(
            model_name='route',
            name='students',
        ),
        migrations.AddField(
            model_name='route',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
        ),
    ]
