# Generated by Django 4.2.1 on 2023-09-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_studentexaminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexaminfo',
            name='total_grade_points',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
