# Generated by Django 4.2.1 on 2023-09-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_studentexaminfo_total_grade_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexaminfo',
            name='total_grade_points',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
