# Generated by Django 4.2.1 on 2023-09-27 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_remove_studentexaminfo_position_result_current_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs')),
            ],
            options={
                'verbose_name': 'Staff Role Assignment',
                'verbose_name_plural': 'Staff Role Assignments',
            },
        ),
    ]
