# Generated by Django 4.2.1 on 2023-10-02 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_staffroleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, to='student_management_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.car')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.route')),
                ('students', models.ManyToManyField(blank=True, to='student_management_app.students')),
            ],
        ),
    ]
