# Generated by Django 4.2.1 on 2023-10-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_route_transportationrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationrecord',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='transportationrecord',
            name='departure_time',
        ),
    ]
