# Generated by Django 4.2.1 on 2023-10-02 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_transportationattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationattendance',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.schooldriver'),
        ),
    ]
