# Generated by Django 4.2.1 on 2023-10-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_transportationattendance_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='routes', to='student_management_app.students'),
        ),
    ]
