# Generated by Django 4.2.1 on 2023-09-27 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_staffroleassignment'),
        ('financial_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.staffs'),
        ),
    ]
