# Generated by Django 4.2.1 on 2023-11-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_remove_staffs_availability_and_more'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_model',
            name='group',
        ),
        migrations.AddField(
            model_name='exam_model',
            name='selected_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.class_level'),
        ),
    ]
