# Generated by Django 4.2.1 on 2023-11-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_model_group_exam_model_selected_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
